### ISSUE TITLE
File missing - sqlserializer.h

### ISSUE THREAD

**Issue by diesel437** [HamedMasafi/Nut#55]
Theres a file missing while trying to build on Windows with MSVC2015 / Qt5.12

D:\Projetos\Nut..\..\Nut\src\generators\sqlgeneratorbase.cpp:34: error: C1083: NÆo ‚ poss¡vel abrir arquivo incluir: **'sqlserializer.h': No such file or directory**

**Comment by diesel437** [comment]
Oh, found it, its a submodule.
Sorry!
